name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        apt update
        apt install git zip unzip
        git clone https://github.com/xdrfvgz/APIGardian
        cd APIGardian/system_setup
        bash ./install.sh
        cd ..
        cp app/build/outputs/apk/debug/app-debug.apk $HOME/

    - name: Upload APK
      uses: actions/upload-artifact@v3  # Aktualisiert auf v3
      with:
        name: app-debug.apk
        path: $HOME/app-debug.apk
        if-no-files-found: error
